name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Prereqs
      run: sudo apt install libudns-dev libsqlite3-dev libexpat1-dev pkg-config
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: OFF
        run_tests: OFF
